### PR TITLE
Use new freva-service config.

### PR DESCRIPTION
**Pull request by antarcticrainforest**
This should be straight forward. It only reflects the changes from the PR in freva-service-config.

### CODE REVIEW

**Review by MoSHad91 — APPROVED** [review]
As we all discussed changes in the last PR, when you got green light from CI then LGTM 🚀

**Comment by antarcticrainforest** [comment]
Sorry, I will need to add more changes to the freva-sevice repo!

**Comment by MoSHad91** [comment]
i think u need to update the submodule here to the latest hash ...

**Comment by antarcticrainforest** [comment]
I hope that should do it.

**Pull request merged**
